[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = [ "@ampproject/toolbox-optimizer", "sharp"]
  included_files = ["!node_modules/chrome-aws-lambda/bin/chromium.br"]